# FEATURE SCALING EXERCISE

# Imports

In [ ]:
!pip install scikit-learn==1.1.3

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.8/30.8 MB 46.8 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2


In [ ]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston
from sklearn.preprocessing import MinMaxScaler,StandardScaler

# Problem: The Boston House Pricing

## Dataset Description

Scikit-learn toy datasets: scikit-learn package of Python comes with a few small standard datasets that do not require to download any file from some external website.
https://scikit-learn.org/stable/datasets/toy_dataset.html

This Boston House Pricingdata has been taken from a reaserch paper, which can be found at
[Source: Original research paper](https://deepblue.lib.umich.edu/bitstream/handle/2027.42/22636/0000186.pdf?sequence=1&isAllowed=y)

## Loading Data

In [ ]:
#loading the dataset from sklearn.
boston_dataset = load_boston()

/usr/local/lib/python3.9/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.


## Exploring Data

In [ ]:
#Let us view what we have downloaded using the following command.
boston_dataset
#It displays the downloaded dataset in its raw form.

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [ ]:
#Let us see the type of 'data'.
type(boston_dataset)
#It shows a special object type bunch.

sklearn.utils._bunch.Bunch

In [ ]:
#dir function gives list of all the attributes and methods for this object bunch.
dir(boston_dataset)

['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'target']

In [ ]:
#Let us explore these attributes one by one.
#Printing description of the dataset using the DESCR attribute.
print(boston_dataset.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [ ]:
#Printing the 'data' attribute.
print(boston_dataset.data)
#These are 13 attributes stored in a ndarray (try writing command to check/verify this datatype).

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [ ]:
#Printing the 'feature_names' attribute.
print(boston_dataset.feature_names)

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [ ]:
#Printing the 'file_name' attribute.
print(boston_dataset.filename)
#This is the csv file that we have downloaded.

boston_house_prices.csv


In [ ]:
#Printing the 'target' attribute.
print(boston_dataset.target)
#Target is another ndarray; use type function to verify this.

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

In [ ]:
#TASK FOR YOU
#Print shape of the two ndarrays of features (boston_dataset.data) and target (boston_dataset.target).
np.shape(boston_dataset.data)

(506, 13)

In [ ]:
np.shape(boston_dataset.target)

(506,)

## Creating Dataframe

In [ ]:
#Let us create a dataframe from the two ndarrays 'data' and 'target' from boston_dataset.
dataset = pd.DataFrame(data=boston_dataset.data, columns=boston_dataset.feature_names)
#Add column with the price (target).
dataset['PRICE'] = boston_dataset.target

In [ ]:
#let's see the dataframe we have created.
dataset

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  PRICE  
0       15.3  396.90   4.98   24.0  
1       17.8  396.90   9.14   21.6  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
..       ...     ...    ...    ...  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[506 rows x 14 columns]

In [ ]:
#TASK FOR YOU
#Run info and describe methods on this dataframe to explore the statistics info
dataset.info

<bound method DataFrame.info of         CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  PRICE  
0       15.3  396.90   4.98   

In [ ]:
dataset.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT       PRICE  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

## Scaling Data - Normalization

In [ ]:
#Let us normalize the PTRATIO column using the normalization formula \discussed in class.
dataset['PTRATIO']=(dataset['PTRATIO']-dataset['PTRATIO'].min())/(dataset['PTRATIO'].max()-dataset['PTRATIO'].min())
#Let us check the dataset
dataset

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

      PTRATIO       B  LSTAT  PRICE  
0    0.287234  396.90   4.98   24.0  
1    0.553191  396.90   9.14   21.6  
2    0.553191  392.83   4.03   34.7  
3    0.648936  394.63   2.94   33.4  
4    0.648936  396.90   5.33   36.2  
..        ...     ...    ...    ...  
501  0.893617  391.99   9.67   22.4  
502  0.893617  396.90   9.08   20.6  
503  0.893617  396.90   5.64   23.9  
504  0.893617  393.45   6.48   22.0  
505  0.893617  396.90   7.88   11.9  

[506 rows x 14 columns]

In [ ]:
#Let us check the min and max value of this normalized column now.
print('Minimum value is',dataset['PTRATIO'].min())
print('Maximum value is',dataset['PTRATIO'].max())

Minimum value is 0.0
Maximum value is 1.0


In [ ]:
#An alternate way is to use methods from sklearn package.
#Let us use this alternate method now to normalize LSTAT column.

#It is a 2-step process. We define an object of MinMaxScaler type first,
#and then call the method fit_transform on this object to perform normalization.
#The fit_transform method takes and ndarray of shape (n_samples, n_features).

#Defining min-max scaler object
minmax_scaler = MinMaxScaler()

#Normailize data
#dataset['LSTAT']=pd.DataFrame(minmax_scaler.fit_transform(dataset[['LSTAT']]))
#Note that fit_transform method returns a ndarray, so we need to typecast it back to dataframe before placong it back into out dataset.

#this method can be run on whole dataset at once to normalize the all the columns in one go.
#Try it ouit if you want using the following command.
column_headers=['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','PRICE']
dataset=pd.DataFrame(minmax_scaler.fit_transform(dataset),columns=column_headers)
dataset

CRIM    ZN     INDUS  CHAS       NOX        RM       AGE       DIS  \
0    0.000000  0.18  0.067815   0.0  0.314815  0.577505  0.641607  0.269203   
1    0.000236  0.00  0.242302   0.0  0.172840  0.547998  0.782698  0.348962   
2    0.000236  0.00  0.242302   0.0  0.172840  0.694386  0.599382  0.348962   
3    0.000293  0.00  0.063050   0.0  0.150206  0.658555  0.441813  0.448545   
4    0.000705  0.00  0.063050   0.0  0.150206  0.687105  0.528321  0.448545   
..        ...   ...       ...   ...       ...       ...       ...       ...   
501  0.000633  0.00  0.420455   0.0  0.386831  0.580954  0.681771  0.122671   
502  0.000438  0.00  0.420455   0.0  0.386831  0.490324  0.760041  0.105293   
503  0.000612  0.00  0.420455   0.0  0.386831  0.654340  0.907312  0.094381   
504  0.001161  0.00  0.420455   0.0  0.386831  0.619467  0.889804  0.114514   
505  0.000462  0.00  0.420455   0.0  0.386831  0.473079  0.802266  0.125072   

          RAD       TAX   PTRATIO         B     LSTAT     PRICE  
0    0.000000  0.208015  0.287234  1.000000  0.089680  0.422222  
1    0.043478  0.104962  0.553191  1.000000  0.204470  0.368889  
2    0.043478  0.104962  0.553191  0.989737  0.063466  0.660000  
3    0.086957  0.066794  0.648936  0.994276  0.033389  0.631111  
4    0.086957  0.066794  0.648936  1.000000  0.099338  0.693333  
..        ...       ...       ...       ...       ...       ...  
501  0.000000  0.164122  0.893617  0.987619  0.219095  0.386667  
502  0.000000  0.164122  0.893617  1.000000  0.202815  0.346667  
503  0.000000  0.164122  0.893617  1.000000  0.107892  0.420000  
504  0.000000  0.164122  0.893617  0.991301  0.131071  0.377778  
505  0.000000  0.164122  0.893617  1.000000  0.169702  0.153333  

[506 rows x 14 columns]

In [ ]:
#Let us check the min and max value of this normalized column now.
print('Minimum value is',dataset['LSTAT'].min())
print('Maximum value is',dataset['LSTAT'].max())

Minimum value is 0.0
Maximum value is 0.9999999999999998


## Scaling Data - Standardization

In [ ]:
#Let us run describe method and observe standard deviation and mean of various features.
dataset.describe()
# see row 2 and row 3 for mean and standard deviation respectively.

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     0.040544    0.113636    0.391378    0.069170    0.349167    0.521869   
std      0.096679    0.233225    0.251479    0.253994    0.238431    0.134627   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000851    0.000000    0.173387    0.000000    0.131687    0.445392   
50%      0.002812    0.000000    0.338343    0.000000    0.314815    0.507281   
75%      0.041258    0.125000    0.646628    0.000000    0.491770    0.586798   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     0.676364    0.242381    0.371713    0.422208    0.622929    0.898568   
std      0.289896    0.191482    0.378576    0.321636    0.230313    0.230205   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.433831    0.088259    0.130435    0.175573    0.510638    0.945730   
50%      0.768280    0.188949    0.173913    0.272901    0.686170    0.986232   
75%      0.938980    0.369088    1.000000    0.914122    0.808511    0.998298   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

            LSTAT       PRICE  
count  506.000000  506.000000  
mean     0.301409    0.389618  
std      0.197049    0.204380  
min      0.000000    0.000000  
25%      0.144040    0.267222  
50%      0.265728    0.360000  
75%      0.420116    0.444444  
max      1.000000    1.000000

In [ ]:
#Let us atndardize the ZN column.
#std and mean are the methods that can be used to find mean and standard deviation of a feature or all features.
dataset['ZN']=(dataset['ZN']-dataset['ZN'].mean())/dataset['ZN'].std()
#Let us check the dataset description now.
dataset.describe()

CRIM            ZN       INDUS        CHAS         NOX  \
count  506.000000  5.060000e+02  506.000000  506.000000  506.000000   
mean     0.040544  5.090351e-17    0.391378    0.069170    0.349167   
std      0.096679  1.000000e+00    0.251479    0.253994    0.238431   
min      0.000000 -4.872402e-01    0.000000    0.000000    0.000000   
25%      0.000851 -4.872402e-01    0.173387    0.000000    0.131687   
50%      0.002812 -4.872402e-01    0.338343    0.000000    0.314815   
75%      0.041258  4.872402e-02    0.646628    0.000000    0.491770   
max      1.000000  3.800473e+00    1.000000    1.000000    1.000000   

               RM         AGE         DIS         RAD         TAX     PTRATIO  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     0.521869    0.676364    0.242381    0.371713    0.422208    0.622929   
std      0.134627    0.289896    0.191482    0.378576    0.321636    0.230313   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.445392    0.433831    0.088259    0.130435    0.175573    0.510638   
50%      0.507281    0.768280    0.188949    0.173913    0.272901    0.686170   
75%      0.586798    0.938980    0.369088    1.000000    0.914122    0.808511   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

                B       LSTAT       PRICE  
count  506.000000  506.000000  506.000000  
mean     0.898568    0.301409    0.389618  
std      0.230205    0.197049    0.204380  
min      0.000000    0.000000    0.000000  
25%      0.945730    0.144040    0.267222  
50%      0.986232    0.265728    0.360000  
75%      0.998298    0.420116    0.444444  
max      1.000000    1.000000    1.000000

In [ ]:
#Let us view the dataset too.
dataset

CRIM        ZN     INDUS  CHAS       NOX        RM       AGE  \
0    0.000000  0.284548  0.067815   0.0  0.314815  0.577505  0.641607   
1    0.000236 -0.487240  0.242302   0.0  0.172840  0.547998  0.782698   
2    0.000236 -0.487240  0.242302   0.0  0.172840  0.694386  0.599382   
3    0.000293 -0.487240  0.063050   0.0  0.150206  0.658555  0.441813   
4    0.000705 -0.487240  0.063050   0.0  0.150206  0.687105  0.528321   
..        ...       ...       ...   ...       ...       ...       ...   
501  0.000633 -0.487240  0.420455   0.0  0.386831  0.580954  0.681771   
502  0.000438 -0.487240  0.420455   0.0  0.386831  0.490324  0.760041   
503  0.000612 -0.487240  0.420455   0.0  0.386831  0.654340  0.907312   
504  0.001161 -0.487240  0.420455   0.0  0.386831  0.619467  0.889804   
505  0.000462 -0.487240  0.420455   0.0  0.386831  0.473079  0.802266   

          DIS       RAD       TAX   PTRATIO         B     LSTAT     PRICE  
0    0.269203  0.000000  0.208015  0.287234  1.000000  0.089680  0.422222  
1    0.348962  0.043478  0.104962  0.553191  1.000000  0.204470  0.368889  
2    0.348962  0.043478  0.104962  0.553191  0.989737  0.063466  0.660000  
3    0.448545  0.086957  0.066794  0.648936  0.994276  0.033389  0.631111  
4    0.448545  0.086957  0.066794  0.648936  1.000000  0.099338  0.693333  
..        ...       ...       ...       ...       ...       ...       ...  
501  0.122671  0.000000  0.164122  0.893617  0.987619  0.219095  0.386667  
502  0.105293  0.000000  0.164122  0.893617  1.000000  0.202815  0.346667  
503  0.094381  0.000000  0.164122  0.893617  1.000000  0.107892  0.420000  
504  0.114514  0.000000  0.164122  0.893617  0.991301  0.131071  0.377778  
505  0.125072  0.000000  0.164122  0.893617  1.000000  0.169702  0.153333  

[506 rows x 14 columns]

In [ ]:
#Let us check the min and max value of this normalized column now.
print('Minimum value is',dataset['ZN'].min())
print('Maximum value is',dataset['ZN'].max())

Minimum value is -0.4872401872268243
Maximum value is 3.8004734603692296


In [ ]:
#An alternate way is to use methods from skleyarn package.
#Let us use this alternate method now to normalize INDUS column.

#It is a 2-step process. We define an object of StandardScaler type first,
#and then call the method fit_transform on this object to perform standardization.
#The fit_transform method takes and ndarray of shape (n_samples, n_features).

#Defining standard scaler object
stan_scaler = StandardScaler()

#Normailize data
dataset['INDUS']=pd.DataFrame(stan_scaler.fit_transform(dataset[['INDUS']]))
#Note that fit_transform method returns a ndarray, so we need to typecast it back to dataframe before placong it back into out dataset.

#this method can be run on whole dataset at once to normalize the all the columns in one go.
#Try it ouit if you want using the following command.
#dataset=pd.DataFrame(stan_scaler.fit_transform(dataset))

In [ ]:
#Let us check the dataset description now.
dataset.describe()

CRIM            ZN         INDUS        CHAS         NOX  \
count  506.000000  5.060000e+02  5.060000e+02  506.000000  506.000000   
mean     0.040544  5.090351e-17  1.404235e-17    0.069170    0.349167   
std      0.096679  1.000000e+00  1.000990e+00    0.253994    0.238431   
min      0.000000 -4.872402e-01 -1.557842e+00    0.000000    0.000000   
25%      0.000851 -4.872402e-01 -8.676906e-01    0.000000    0.131687   
50%      0.002812 -4.872402e-01 -2.110985e-01    0.000000    0.314815   
75%      0.041258  4.872402e-02  1.015999e+00    0.000000    0.491770   
max      1.000000  3.800473e+00  2.422565e+00    1.000000    1.000000   

               RM         AGE         DIS         RAD         TAX     PTRATIO  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     0.521869    0.676364    0.242381    0.371713    0.422208    0.622929   
std      0.134627    0.289896    0.191482    0.378576    0.321636    0.230313   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.445392    0.433831    0.088259    0.130435    0.175573    0.510638   
50%      0.507281    0.768280    0.188949    0.173913    0.272901    0.686170   
75%      0.586798    0.938980    0.369088    1.000000    0.914122    0.808511   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

                B       LSTAT       PRICE  
count  506.000000  506.000000  506.000000  
mean     0.898568    0.301409    0.389618  
std      0.230205    0.197049    0.204380  
min      0.000000    0.000000    0.000000  
25%      0.945730    0.144040    0.267222  
50%      0.986232    0.265728    0.360000  
75%      0.998298    0.420116    0.444444  
max      1.000000    1.000000    1.000000

In [ ]:
#Let us check the min and max value of this normalized column now.
print('Minimum value is',dataset['INDUS'].min())
print('Maximum value is',dataset['INDUS'].max())
#observe the range is pretty much similar to that of ZN that we standardized earlier.

Minimum value is -1.5578417886292544
Maximum value is 2.422565163932244
